name: fastapi-nginx

services:
  fastapi:
    build: ./app
    container_name: fastapi_app
    expose:
      - 8000
    networks:
      - app-network

  nginx:
    build: ./nginx
    container_name: nginx_proxy
    ports:
      - "80:80"
    depends_on:
      - fastapi
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
