# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: glossary.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "glossary.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0eglossary.proto\x12\x08glossary"\x07\n\x05\x45mpty"\x1f\n\x0fTermNameRequest\x12\x0c\n\x04name\x18\x01 \x01(\t"\x1a\n\tTermNames\x12\r\n\x05names\x18\x01 \x03(\t"O\n\x0cTermResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\r\n\x05\x66ound\x18\x03 \x01(\x08\x12\r\n\x05\x65rror\x18\x04 \x01(\t"6\n\x11TermCreateRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t"T\n\x11TermUpdateRequest\x12\x14\n\x0c\x63urrent_name\x18\x01 \x01(\t\x12\x10\n\x08new_name\x18\x02 \x01(\t\x12\x17\n\x0fnew_description\x18\x03 \x01(\t"+\n\x0e\x44\x65leteResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\xcb\x02\n\x0fGlossaryService\x12\x31\n\tListTerms\x12\x0f.glossary.Empty\x1a\x13.glossary.TermNames\x12<\n\x07GetTerm\x12\x19.glossary.TermNameRequest\x1a\x16.glossary.TermResponse\x12\x41\n\nCreateTerm\x12\x1b.glossary.TermCreateRequest\x1a\x16.glossary.TermResponse\x12\x41\n\nUpdateTerm\x12\x1b.glossary.TermUpdateRequest\x1a\x16.glossary.TermResponse\x12\x41\n\nDeleteTerm\x12\x19.glossary.TermNameRequest\x1a\x18.glossary.DeleteResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "glossary_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_EMPTY"]._serialized_start = 28
    _globals["_EMPTY"]._serialized_end = 35
    _globals["_TERMNAMEREQUEST"]._serialized_start = 37
    _globals["_TERMNAMEREQUEST"]._serialized_end = 68
    _globals["_TERMNAMES"]._serialized_start = 70
    _globals["_TERMNAMES"]._serialized_end = 96
    _globals["_TERMRESPONSE"]._serialized_start = 98
    _globals["_TERMRESPONSE"]._serialized_end = 177
    _globals["_TERMCREATEREQUEST"]._serialized_start = 179
    _globals["_TERMCREATEREQUEST"]._serialized_end = 233
    _globals["_TERMUPDATEREQUEST"]._serialized_start = 235
    _globals["_TERMUPDATEREQUEST"]._serialized_end = 319
    _globals["_DELETERESPONSE"]._serialized_start = 321
    _globals["_DELETERESPONSE"]._serialized_end = 364
    _globals["_GLOSSARYSERVICE"]._serialized_start = 367
    _globals["_GLOSSARYSERVICE"]._serialized_end = 698
# @@protoc_insertion_point(module_scope)
